services:
  app:
    build: .
    command: mprof run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=julo.settings
    depends_on:
      - db
      - message-broker
    networks:
      - django-exercise-network

  celery-worker:
    build: .
    command: celery --app julo worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=julo.settings
    depends_on:
      - db
      - message-broker
    networks:
      - django-exercise-network

  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - django-exercise-network

  message-broker:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.rabbitmq
    networks:
      - django-exercise-network

volumes:
  db:
    driver: local

networks:
  django-exercise-network: